- name: install apache on web servers
  tags: apache
  ansible.builtin.package:
    name:
      - "{{ apache_package }}"

- name: ensure apache is running
  tags: apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started

- name: change email address for admin
  tags: apache,redhat
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebodysomewhere.net
  when: ansible_distribution == "RedHat"
  register: apache

- name: restart apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: restarted
  when: apache.changed
