- name: install apache on web server (ubuntu)
  tags: apache,ubuntu
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
  when: ansible_distribution == "Ubuntu"

- name: install apache on web server (RedHat)
  tags: apache,redhat
  ansible.builtin.dnf:
    name: httpd
  when: ansible_distribution == "RedHat"

- name: ensure apache is running (ubuntu)
  tags: apache,ubuntu
  ansible.builtin.service:
    name: apache2
    state: started
  when: ansible_distribution == "Ubuntu"

- name: ensure apache is running (RedHat)
  tags: apache,redhat
  ansible.builtin.service:
    name: httpd
    state: started
  when: ansible_distribution == "RedHat"

- name: change email address for admin
  tags: apache,fedora
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^ServerAdmin'
    line: ServerAdmin someboy@somewhere.com
  when: ansible_distribution == "RedHat"
  register: httpd

- name: restart httpd (RedHat)
  tags: apacha,fedora
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy html file for site
  tags: apache,ubuntu
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
